name: Extract Maven Artifacts
description: Extract Maven Artifacts uploaded by the build-infinispan action
inputs:
  run_id:
    description: Run id if different than current run (i.e. using workflow_run)
    default: ""
runs:
  using: composite
  steps:
    - name: Download Infinispan Maven artifacts with run_id
      if: ${{ inputs.run_id }} != ""
      uses: actions/download-artifact@v4
      with:
        name: m2-infinispan.tzts
        run_id: ${{ inputs.run_id }}

    - name: Download Infinispan Maven artifacts
      if: ${{ inputs.run_id }} == ""
      uses: actions/download-artifact@v4
      with:
        name: m2-infinispan.tzts
        run_id: ${{ inputs.run_id }}

    - name: Extract Infinispan Maven artifacts
      shell: bash
      run: tar -C ~/ --use-compress-program="zstd -d" -xf m2-infinispan.tzts
