name: Labeller
on:
  pull_request_target:
    types: [closed]

jobs:
  label:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write

    steps:
      - name: Log something
        run:
         echo "HEY! I'M RUNNING"
