name: On PR Open or Push Do Test
on:
   workflow_run:
      workflows: [On PR Open or Push Do Build]
      types: [completed]

concurrency:
  # Only cancel jobs for PR updates
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  get-info:
   runs-on: ubuntu-latest
   outputs:
      run_id: ${{ steps.get-info.outputs.run_id }}
      head_sha: ${{ steps.get-info.outputs.head_sha }}
      event: ${{ steps.get-info.outputs.event }}
      head_branch: ${{ steps.get-info.outputs.head_branch }}
   steps:
     - name: Get Info
       id: get-info
       uses: actions/github-script@v7
       with:
         result-encoding: string
         script: |
            core.info(JSON.stringify(context.payload.workflow_run))
            core.setOutput("run_id", context.payload.workflow_run.id)
            core.setOutput("head_sha", context.payload.workflow_run.head_sha)
            core.setOutput("event", context.payload.workflow_run.event)
            core.setOutput("head_branch", context.payload.workflow_run.head_branch)

  ci-build-test-pr:
    needs: get-info
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Maven Build and Test
    runs-on: ubuntu-latest
    env:
      MAVEN_OPTS: "-Xmx1500m -XX:+HeapDumpOnOutOfMemoryError"
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: ./.github/actions/setup-java

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: 21
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Maven Artifacts
        uses: ./.github/actions/extract-maven-artifacts
        with:
         run_id: ${{ needs.get-info.outputs.run_id }}

      - name: Maven Test
        run: >
            ./mvnw verify -s maven-settings.xml -V -B -e -DrerunFailingTestsCount=2
            -Dmaven.test.failure.ignore=true -Dansi.strip=true -Pnative

      - name: Archive commit sha PR
        if: >
          (success() || failure()) &&
          github.event_name == 'pull_request'
        run: |
           echo -n ${{ needs.get-info.outputs.run_id }} > github-sha.txt

      - name: Archive commit sha push
        if: >
          (success() || failure()) &&
          github.event_name == 'push'
        run: |
           echo -n $GITHUB_SHA > github-sha.txt

      - name: Archive surefire test report
        if: (success() || failure())
        uses: actions/upload-artifact@v4
        with:
          name: surefire-test-report
          path: |
            **/surefire-reports/TEST-*.xml
            **/*.dump*
            **/hs_err_*
            github-sha.txt
            !**/target/*-reports*/**/TEST-*FLAKY.xml

# Create artifact with branch name and surefile flaky test report
      - name: Check flaky report existence
        if: success() || failure()
        id: check_flaky_report
        uses: andstor/file-existence-action@v3
        with:
          files: "**/target/*-reports*/**/TEST-*FLAKY.xml"

      - name: Archive base_ref
        if: (success() || failure()) && steps.check_flaky_report.outputs.files_exists == 'true'
        env:
          TARGET_BRANCH: ${{ needs.get-info.outputs.head_branch }}
          EVENT_NAME: ${{ needs.get-info.outputs.event }}
          EVENT_NUMBER: ${{ needs.get-info.outputs.run_id }}
        run: |
          echo -n $TARGET_BRANCH > target-branch.txt
          echo -n $EVENT_NAME > event-name.txt
          echo -n $EVENT_NUMBER > event-number.txt

      - name: Archive flaky test report
        if: (success() || failure()) && steps.check_flaky_report.outputs.files_exists == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: flaky-test-report
          path: |
            **/target/*-reports*/**/TEST-*FLAKY.xml
            target-branch.txt
            event-name.txt
            event-number.txt

  db:
    needs: get-info
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dbs:
          - mssql
          - oracle
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: ./.github/actions/setup-java

      - name: Extract Maven Artifacts
        uses: ./.github/actions/extract-maven-artifacts
        with:
         run_id: ${{ needs.get-info.outputs.run_id }}

      - name: Infinispan Version
        run: echo "ISPN_VERSION=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Download Infinispan Server
        uses: actions/download-artifact@v4
        with:
          name: infinispan-dist

      - name: Extract Infinispan Server
        run: |
          cd /tmp
          unzip ${GITHUB_WORKSPACE}/infinispan-server-${ISPN_VERSION}.zip

      - name: Test
        run: |
          ./mvnw verify -s maven-settings.xml -B -e -pl server/tests --fail-at-end \
            -Dansi.strip=true \
            -DdefaultTestGroup=database \
            -Dorg.infinispan.test.database.types=${{ matrix.dbs }} \
            -Dorg.infinispan.test.server.dir=/tmp/infinispan-server-${ISPN_VERSION}
