name: Publish Test Report
on:
   workflow_run:
     workflows: [Test]
     types: [completed]
jobs:
   publish:
      if: github.event.workflow_run.conclusion == 'success'
      name: Publish Surefire Report
      runs-on: ubuntu-latest
      steps:
        - name: Install xmlstarlet tool
          shell: bash
          run: |
             sudo apt-get update
             sudo apt-get install -y xmlstarlet

# Downloading surefire report artifact containing
# zip file with reports and file
# containing commit sha
        - name: Download a Build Artifact
          uses: actions/download-artifact@v4.1.8
          with:
            name: surefire-test-report
            github-token: ${{ github.token }}
            run-id: ${{ github.event.workflow_run.id }}

        - name: Get github sha
          id: github_sha
          uses: juliangruber/read-file-action@v1
          with:
            path: ./github-sha.txt

        - name: Remove flaky tests from failure report
          if: (success() || failure())
          run: |
               find . -name "TEST-*Test.xml" | while read f
                   do
                      xmlstarlet ed --inplace -d "//testcase[flakyFailure]" "$f"
                   done

        - name: Publish Test Report
          if: success() || failure()
          uses: ScaCap/action-surefire-report@v1.8.0
          with:
            commit: ${{ steps.github_sha.outputs.content }}
            check_name: Test Report Result
            report_paths: |
              **/surefire-reports/TEST-*.xml

        - name: set-commit-status-pending
          if: success() || failure()
          env:
            MIN_TEST_NUM: 30000
          uses: myrotvorets/set-commit-status-action@v2.0.1
          with:
                status: failure
                sha: ${{ steps.github_sha.outputs.content }}
                context: Tests number check
                description: Fail. $COUNT test ran, minimum required is $MIN_TEST_NUM
                targetUrl: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

